name: Docker Build and Push

on:
  push:
    branches:
      - main
  # Atau bisa ditambahkan event lain seperti pull_request atau schedule

jobs:
  build:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu di GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Pastikan Anda sudah menyimpan username dan password Docker Hub Anda di GitHub Secrets

      - name: Build Docker image
        run: |
          docker build -t bimatech/demo-app:jma-2.0 .

      - name: Push Docker image to Docker Hub
        run: |
          docker push bimatech/demo-app:jma-2.0
